#!/usr/bin/env python3
"""
Regenerate the LightSports launcher icon.

The mark is a ball: one ring and two seams. White line art on black, matching the
icon language of the sibling Light Phone III tools. A ball is the only shape that
reads as "sport" without picking a sport, which matters for an app carrying baseball,
football, basketball, hockey, soccer and motor racing at once.

Geometry lives once, in the 108x108 adaptive-icon canvas, and is emitted twice — as
Android vector paths and as raster fallbacks. The seams are cubic beziers rather than
SVG arcs: arcs need their large-arc and sweep flags rethought under scaling, and that
is exactly the trap that mangled an earlier icon in this family.

    python3 scripts/generate_icon.py

Needs Pillow. Rewrites app/src/main/res/{drawable,mipmap-*}.
"""

from __future__ import annotations

import os

from PIL import Image, ImageDraw

RES = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "res")

CANVAS = 108
SAFE = (18, 90)
STROKE = 5.0

CENTRE = (54.0, 54.0)
RADIUS = 26.0  # centreline; outer edge lands at RADIUS + STROKE/2

# Each seam is a single cubic: endpoints near the ring, controls pushed inward so the
# curve bows the way a baseball seam does.
# Endpoints sit exactly on the ring: at y = 31.5 the circle is at x = 54 +/- 13.04,
# and an endpoint even a pixel outside leaves a visible spur past the outline.
SEAMS = (
    ((41.0, 31.5), (49.5, 42.0), (49.5, 66.0), (41.0, 76.5)),
    ((67.0, 31.5), (58.5, 42.0), (58.5, 66.0), (67.0, 76.5)),
)

DENSITIES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}
SUPERSAMPLE = 8
SEAM_STEPS = 72


def cubic(p0, p1, p2, p3, t):
    u = 1.0 - t
    x = u * u * u * p0[0] + 3 * u * u * t * p1[0] + 3 * u * t * t * p2[0] + t * t * t * p3[0]
    y = u * u * u * p0[1] + 3 * u * u * t * p1[1] + 3 * u * t * t * p2[1] + t * t * t * p3[1]
    return x, y


def check_safe_zone() -> None:
    lo, hi = SAFE
    edge = STROKE / 2
    cx, cy = CENTRE
    extents = [
        (cx - RADIUS - edge, cy),
        (cx + RADIUS + edge, cy),
        (cx, cy - RADIUS - edge),
        (cx, cy + RADIUS + edge),
    ]
    for seam in SEAMS:
        for i in range(SEAM_STEPS + 1):
            x, y = cubic(*seam, i / SEAM_STEPS)
            extents.append((x, y))
    for x, y in extents:
        assert lo <= x <= hi and lo <= y <= hi, f"({x:.1f}, {y:.1f}) escapes the safe zone"


def ring_path() -> str:
    cx, cy = CENTRE
    r = RADIUS
    return (
        f"M {cx - r},{cy} A {r},{r} 0 1 0 {cx + r},{cy} "
        f"A {r},{r} 0 1 0 {cx - r},{cy} Z"
    )


def seam_path(seam) -> str:
    (x0, y0), (x1, y1), (x2, y2), (x3, y3) = seam
    return f"M {x0},{y0} C {x1},{y1} {x2},{y2} {x3},{y3}"


def write_vectors() -> None:
    background = """<?xml version="1.0" encoding="utf-8"?>
<!-- Pure black. On the Light Phone III's OLED these pixels are simply off. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path
        android:fillColor="#000000"
        android:pathData="M0,0h108v108h-108z" />
</vector>
"""

    def stroked(path: str) -> str:
        return (
            "    <path\n"
            '        android:fillColor="#00000000"\n'
            '        android:strokeColor="#FFFFFF"\n'
            f'        android:strokeWidth="{STROKE}"\n'
            '        android:strokeLineCap="round"\n'
            f'        android:pathData="{path}" />'
        )

    paths = "\n".join([stroked(ring_path())] + [stroked(seam_path(s)) for s in SEAMS])
    foreground = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate_icon.py; edit the geometry there, not here. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
{paths}
</vector>
"""

    adaptive = """<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
"""

    os.makedirs(os.path.join(RES, "drawable"), exist_ok=True)
    os.makedirs(os.path.join(RES, "mipmap-anydpi-v26"), exist_ok=True)
    with open(os.path.join(RES, "drawable", "ic_launcher_background.xml"), "w") as f:
        f.write(background)
    with open(os.path.join(RES, "drawable", "ic_launcher_foreground.xml"), "w") as f:
        f.write(foreground)
    for name in ("ic_launcher", "ic_launcher_round"):
        with open(os.path.join(RES, "mipmap-anydpi-v26", f"{name}.xml"), "w") as f:
            f.write(adaptive)


def render(px: int, circular: bool) -> Image.Image:
    """
    Draw at SUPERSAMPLE times the target size and downsample. The legacy mipmaps are
    the whole icon rather than an adaptive foreground, so the art is scaled to the
    66/108 that a launcher mask leaves visible.
    """
    size = px * SUPERSAMPLE
    scale = size / CANVAS * (66.0 / 108.0)
    offset = size / 2 - CANVAS / 2 * scale

    def to_px(x: float, y: float):
        return x * scale + offset, y * scale + offset

    image = Image.new("RGBA", (size, size), (0, 0, 0, 255))
    draw = ImageDraw.Draw(image)
    width = max(1, round(STROKE * scale))

    cx, cy = CENTRE
    left, top = to_px(cx - RADIUS, cy - RADIUS)
    right, bottom = to_px(cx + RADIUS, cy + RADIUS)
    draw.ellipse([left, top, right, bottom], outline=(255, 255, 255, 255), width=width)

    for seam in SEAMS:
        points = [to_px(*cubic(*seam, i / SEAM_STEPS)) for i in range(SEAM_STEPS + 1)]
        draw.line(points, fill=(255, 255, 255, 255), width=width, joint="curve")

    if circular:
        mask = Image.new("L", (size, size), 0)
        ImageDraw.Draw(mask).ellipse([0, 0, size - 1, size - 1], fill=255)
        image.putalpha(mask)

    return image.resize((px, px), Image.LANCZOS)


def write_rasters() -> None:
    for dpi, px in DENSITIES.items():
        folder = os.path.join(RES, f"mipmap-{dpi}")
        os.makedirs(folder, exist_ok=True)
        render(px, circular=False).save(os.path.join(folder, "ic_launcher.png"))
        render(px, circular=True).save(os.path.join(folder, "ic_launcher_round.png"))


if __name__ == "__main__":
    check_safe_zone()
    write_vectors()
    write_rasters()
    print("icon regenerated")
